language: python

python:
  - 3.5
  - 3.6
  - nightly

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run --omit=*/lib/* setup.py test

after_success:
  coveralls
